/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.scistor.process.thrift.service;

import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Generated;
import java.nio.ByteBuffer;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-11-08")
public class MasterService {

  public interface Iface {

    public String newTask(String taskId, String xmlContent) throws TException;

    public String registerComponent(String componentName, String mainclass, ByteBuffer componentInfo) throws TException;

  }

  public interface AsyncIface {

    public void newTask(String taskId, String xmlContent, AsyncMethodCallback resultHandler) throws TException;

    public void registerComponent(String componentName, String mainclass, ByteBuffer componentInfo, AsyncMethodCallback resultHandler) throws TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public String newTask(String taskId, String xmlContent) throws TException
    {
      send_newTask(taskId, xmlContent);
      return recv_newTask();
    }

    public void send_newTask(String taskId, String xmlContent) throws TException
    {
      newTask_args args = new newTask_args();
      args.setTaskId(taskId);
      args.setXmlContent(xmlContent);
      sendBase("newTask", args);
    }

    public String recv_newTask() throws TException
    {
      newTask_result result = new newTask_result();
      receiveBase(result, "newTask");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "newTask failed: unknown result");
    }

    public String registerComponent(String componentName, String mainclass, ByteBuffer componentInfo) throws TException
    {
      send_registerComponent(componentName, mainclass, componentInfo);
      return recv_registerComponent();
    }

    public void send_registerComponent(String componentName, String mainclass, ByteBuffer componentInfo) throws TException
    {
      registerComponent_args args = new registerComponent_args();
      args.setComponentName(componentName);
      args.setMainclass(mainclass);
      args.setComponentInfo(componentInfo);
      sendBase("registerComponent", args);
    }

    public String recv_registerComponent() throws TException
    {
      registerComponent_result result = new registerComponent_result();
      receiveBase(result, "registerComponent");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "registerComponent failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void newTask(String taskId, String xmlContent, AsyncMethodCallback resultHandler) throws TException {
      checkReady();
      newTask_call method_call = new newTask_call(taskId, xmlContent, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class newTask_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String taskId;
      private String xmlContent;
      public newTask_call(String taskId, String xmlContent, AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.taskId = taskId;
        this.xmlContent = xmlContent;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("newTask", org.apache.thrift.protocol.TMessageType.CALL, 0));
        newTask_args args = new newTask_args();
        args.setTaskId(taskId);
        args.setXmlContent(xmlContent);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_newTask();
      }
    }

    public void registerComponent(String componentName, String mainclass, ByteBuffer componentInfo, AsyncMethodCallback resultHandler) throws TException {
      checkReady();
      registerComponent_call method_call = new registerComponent_call(componentName, mainclass, componentInfo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class registerComponent_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String componentName;
      private String mainclass;
      private ByteBuffer componentInfo;
      public registerComponent_call(String componentName, String mainclass, ByteBuffer componentInfo, AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.componentName = componentName;
        this.mainclass = mainclass;
        this.componentInfo = componentInfo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("registerComponent", org.apache.thrift.protocol.TMessageType.CALL, 0));
        registerComponent_args args = new registerComponent_args();
        args.setComponentName(componentName);
        args.setMainclass(mainclass);
        args.setComponentInfo(componentInfo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public String getResult() throws TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_registerComponent();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("newTask", new newTask());
      processMap.put("registerComponent", new registerComponent());
      return processMap;
    }

    public static class newTask<I extends Iface> extends org.apache.thrift.ProcessFunction<I, newTask_args> {
      public newTask() {
        super("newTask");
      }

      public newTask_args getEmptyArgsInstance() {
        return new newTask_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public newTask_result getResult(I iface, newTask_args args) throws TException {
        newTask_result result = new newTask_result();
        result.success = iface.newTask(args.taskId, args.xmlContent);
        return result;
      }
    }

    public static class registerComponent<I extends Iface> extends org.apache.thrift.ProcessFunction<I, registerComponent_args> {
      public registerComponent() {
        super("registerComponent");
      }

      public registerComponent_args getEmptyArgsInstance() {
        return new registerComponent_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public registerComponent_result getResult(I iface, registerComponent_args args) throws TException {
        registerComponent_result result = new registerComponent_result();
        result.success = iface.registerComponent(args.componentName, args.mainclass, args.componentInfo);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("newTask", new newTask());
      processMap.put("registerComponent", new registerComponent());
      return processMap;
    }

    public static class newTask<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, newTask_args, String> {
      public newTask() {
        super("newTask");
      }

      public newTask_args getEmptyArgsInstance() {
        return new newTask_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            newTask_result result = new newTask_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            newTask_result result = new newTask_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, newTask_args args, AsyncMethodCallback<String> resultHandler) throws TException {
        iface.newTask(args.taskId, args.xmlContent,resultHandler);
      }
    }

    public static class registerComponent<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, registerComponent_args, String> {
      public registerComponent() {
        super("registerComponent");
      }

      public registerComponent_args getEmptyArgsInstance() {
        return new registerComponent_args();
      }

      public AsyncMethodCallback<String> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<String>() { 
          public void onComplete(String o) {
            registerComponent_result result = new registerComponent_result();
            result.success = o;
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            registerComponent_result result = new registerComponent_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, registerComponent_args args, AsyncMethodCallback<String> resultHandler) throws TException {
        iface.registerComponent(args.componentName, args.mainclass, args.componentInfo,resultHandler);
      }
    }

  }

  public static class newTask_args implements org.apache.thrift.TBase<newTask_args, newTask_args._Fields>, java.io.Serializable, Cloneable, Comparable<newTask_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("newTask_args");

    private static final org.apache.thrift.protocol.TField TASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("taskId", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField XML_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("xmlContent", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new newTask_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new newTask_argsTupleSchemeFactory());
    }

    public String taskId; // required
    public String xmlContent; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      TASK_ID((short)1, "taskId"),
      XML_CONTENT((short)2, "xmlContent");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // TASK_ID
            return TASK_ID;
          case 2: // XML_CONTENT
            return XML_CONTENT;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.TASK_ID, new org.apache.thrift.meta_data.FieldMetaData("taskId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.XML_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("xmlContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(newTask_args.class, metaDataMap);
    }

    public newTask_args() {
    }

    public newTask_args(
      String taskId,
      String xmlContent)
    {
      this();
      this.taskId = taskId;
      this.xmlContent = xmlContent;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public newTask_args(newTask_args other) {
      if (other.isSetTaskId()) {
        this.taskId = other.taskId;
      }
      if (other.isSetXmlContent()) {
        this.xmlContent = other.xmlContent;
      }
    }

    public newTask_args deepCopy() {
      return new newTask_args(this);
    }

    @Override
    public void clear() {
      this.taskId = null;
      this.xmlContent = null;
    }

    public String getTaskId() {
      return this.taskId;
    }

    public newTask_args setTaskId(String taskId) {
      this.taskId = taskId;
      return this;
    }

    public void unsetTaskId() {
      this.taskId = null;
    }

    /** Returns true if field taskId is set (has been assigned a value) and false otherwise */
    public boolean isSetTaskId() {
      return this.taskId != null;
    }

    public void setTaskIdIsSet(boolean value) {
      if (!value) {
        this.taskId = null;
      }
    }

    public String getXmlContent() {
      return this.xmlContent;
    }

    public newTask_args setXmlContent(String xmlContent) {
      this.xmlContent = xmlContent;
      return this;
    }

    public void unsetXmlContent() {
      this.xmlContent = null;
    }

    /** Returns true if field xmlContent is set (has been assigned a value) and false otherwise */
    public boolean isSetXmlContent() {
      return this.xmlContent != null;
    }

    public void setXmlContentIsSet(boolean value) {
      if (!value) {
        this.xmlContent = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case TASK_ID:
        if (value == null) {
          unsetTaskId();
        } else {
          setTaskId((String)value);
        }
        break;

      case XML_CONTENT:
        if (value == null) {
          unsetXmlContent();
        } else {
          setXmlContent((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case TASK_ID:
        return getTaskId();

      case XML_CONTENT:
        return getXmlContent();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case TASK_ID:
        return isSetTaskId();
      case XML_CONTENT:
        return isSetXmlContent();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof newTask_args)
        return this.equals((newTask_args)that);
      return false;
    }

    public boolean equals(newTask_args that) {
      if (that == null)
        return false;

      boolean this_present_taskId = true && this.isSetTaskId();
      boolean that_present_taskId = true && that.isSetTaskId();
      if (this_present_taskId || that_present_taskId) {
        if (!(this_present_taskId && that_present_taskId))
          return false;
        if (!this.taskId.equals(that.taskId))
          return false;
      }

      boolean this_present_xmlContent = true && this.isSetXmlContent();
      boolean that_present_xmlContent = true && that.isSetXmlContent();
      if (this_present_xmlContent || that_present_xmlContent) {
        if (!(this_present_xmlContent && that_present_xmlContent))
          return false;
        if (!this.xmlContent.equals(that.xmlContent))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_taskId = true && (isSetTaskId());
      list.add(present_taskId);
      if (present_taskId)
        list.add(taskId);

      boolean present_xmlContent = true && (isSetXmlContent());
      list.add(present_xmlContent);
      if (present_xmlContent)
        list.add(xmlContent);

      return list.hashCode();
    }

    @Override
    public int compareTo(newTask_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetTaskId()).compareTo(other.isSetTaskId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetTaskId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskId, other.taskId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetXmlContent()).compareTo(other.isSetXmlContent());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetXmlContent()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xmlContent, other.xmlContent);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("newTask_args(");
      boolean first = true;

      sb.append("taskId:");
      if (this.taskId == null) {
        sb.append("null");
      } else {
        sb.append(this.taskId);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("xmlContent:");
      if (this.xmlContent == null) {
        sb.append("null");
      } else {
        sb.append(this.xmlContent);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class newTask_argsStandardSchemeFactory implements SchemeFactory {
      public newTask_argsStandardScheme getScheme() {
        return new newTask_argsStandardScheme();
      }
    }

    private static class newTask_argsStandardScheme extends StandardScheme<newTask_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, newTask_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // TASK_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.taskId = iprot.readString();
                struct.setTaskIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // XML_CONTENT
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.xmlContent = iprot.readString();
                struct.setXmlContentIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, newTask_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.taskId != null) {
          oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
          oprot.writeString(struct.taskId);
          oprot.writeFieldEnd();
        }
        if (struct.xmlContent != null) {
          oprot.writeFieldBegin(XML_CONTENT_FIELD_DESC);
          oprot.writeString(struct.xmlContent);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class newTask_argsTupleSchemeFactory implements SchemeFactory {
      public newTask_argsTupleScheme getScheme() {
        return new newTask_argsTupleScheme();
      }
    }

    private static class newTask_argsTupleScheme extends TupleScheme<newTask_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, newTask_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetTaskId()) {
          optionals.set(0);
        }
        if (struct.isSetXmlContent()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetTaskId()) {
          oprot.writeString(struct.taskId);
        }
        if (struct.isSetXmlContent()) {
          oprot.writeString(struct.xmlContent);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, newTask_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.taskId = iprot.readString();
          struct.setTaskIdIsSet(true);
        }
        if (incoming.get(1)) {
          struct.xmlContent = iprot.readString();
          struct.setXmlContentIsSet(true);
        }
      }
    }

  }

  public static class newTask_result implements org.apache.thrift.TBase<newTask_result, newTask_result._Fields>, java.io.Serializable, Cloneable, Comparable<newTask_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("newTask_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new newTask_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new newTask_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(newTask_result.class, metaDataMap);
    }

    public newTask_result() {
    }

    public newTask_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public newTask_result(newTask_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public newTask_result deepCopy() {
      return new newTask_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public newTask_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof newTask_result)
        return this.equals((newTask_result)that);
      return false;
    }

    public boolean equals(newTask_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(newTask_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("newTask_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class newTask_resultStandardSchemeFactory implements SchemeFactory {
      public newTask_resultStandardScheme getScheme() {
        return new newTask_resultStandardScheme();
      }
    }

    private static class newTask_resultStandardScheme extends StandardScheme<newTask_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, newTask_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, newTask_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class newTask_resultTupleSchemeFactory implements SchemeFactory {
      public newTask_resultTupleScheme getScheme() {
        return new newTask_resultTupleScheme();
      }
    }

    private static class newTask_resultTupleScheme extends TupleScheme<newTask_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, newTask_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, newTask_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

  public static class registerComponent_args implements org.apache.thrift.TBase<registerComponent_args, registerComponent_args._Fields>, java.io.Serializable, Cloneable, Comparable<registerComponent_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerComponent_args");

    private static final org.apache.thrift.protocol.TField COMPONENT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("componentName", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField MAINCLASS_FIELD_DESC = new org.apache.thrift.protocol.TField("mainclass", org.apache.thrift.protocol.TType.STRING, (short)2);
    private static final org.apache.thrift.protocol.TField COMPONENT_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("componentInfo", org.apache.thrift.protocol.TType.STRING, (short)3);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerComponent_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerComponent_argsTupleSchemeFactory());
    }

    public String componentName; // required
    public String mainclass; // required
    public ByteBuffer componentInfo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      COMPONENT_NAME((short)1, "componentName"),
      MAINCLASS((short)2, "mainclass"),
      COMPONENT_INFO((short)3, "componentInfo");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // COMPONENT_NAME
            return COMPONENT_NAME;
          case 2: // MAINCLASS
            return MAINCLASS;
          case 3: // COMPONENT_INFO
            return COMPONENT_INFO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.COMPONENT_NAME, new org.apache.thrift.meta_data.FieldMetaData("componentName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.MAINCLASS, new org.apache.thrift.meta_data.FieldMetaData("mainclass", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.COMPONENT_INFO, new org.apache.thrift.meta_data.FieldMetaData("componentInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , true)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerComponent_args.class, metaDataMap);
    }

    public registerComponent_args() {
    }

    public registerComponent_args(
      String componentName,
      String mainclass,
      ByteBuffer componentInfo)
    {
      this();
      this.componentName = componentName;
      this.mainclass = mainclass;
      this.componentInfo = org.apache.thrift.TBaseHelper.copyBinary(componentInfo);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerComponent_args(registerComponent_args other) {
      if (other.isSetComponentName()) {
        this.componentName = other.componentName;
      }
      if (other.isSetMainclass()) {
        this.mainclass = other.mainclass;
      }
      if (other.isSetComponentInfo()) {
        this.componentInfo = org.apache.thrift.TBaseHelper.copyBinary(other.componentInfo);
      }
    }

    public registerComponent_args deepCopy() {
      return new registerComponent_args(this);
    }

    @Override
    public void clear() {
      this.componentName = null;
      this.mainclass = null;
      this.componentInfo = null;
    }

    public String getComponentName() {
      return this.componentName;
    }

    public registerComponent_args setComponentName(String componentName) {
      this.componentName = componentName;
      return this;
    }

    public void unsetComponentName() {
      this.componentName = null;
    }

    /** Returns true if field componentName is set (has been assigned a value) and false otherwise */
    public boolean isSetComponentName() {
      return this.componentName != null;
    }

    public void setComponentNameIsSet(boolean value) {
      if (!value) {
        this.componentName = null;
      }
    }

    public String getMainclass() {
      return this.mainclass;
    }

    public registerComponent_args setMainclass(String mainclass) {
      this.mainclass = mainclass;
      return this;
    }

    public void unsetMainclass() {
      this.mainclass = null;
    }

    /** Returns true if field mainclass is set (has been assigned a value) and false otherwise */
    public boolean isSetMainclass() {
      return this.mainclass != null;
    }

    public void setMainclassIsSet(boolean value) {
      if (!value) {
        this.mainclass = null;
      }
    }

    public byte[] getComponentInfo() {
      setComponentInfo(org.apache.thrift.TBaseHelper.rightSize(componentInfo));
      return componentInfo == null ? null : componentInfo.array();
    }

    public ByteBuffer bufferForComponentInfo() {
      return org.apache.thrift.TBaseHelper.copyBinary(componentInfo);
    }

    public registerComponent_args setComponentInfo(byte[] componentInfo) {
      this.componentInfo = componentInfo == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(componentInfo, componentInfo.length));
      return this;
    }

    public registerComponent_args setComponentInfo(ByteBuffer componentInfo) {
      this.componentInfo = org.apache.thrift.TBaseHelper.copyBinary(componentInfo);
      return this;
    }

    public void unsetComponentInfo() {
      this.componentInfo = null;
    }

    /** Returns true if field componentInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetComponentInfo() {
      return this.componentInfo != null;
    }

    public void setComponentInfoIsSet(boolean value) {
      if (!value) {
        this.componentInfo = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case COMPONENT_NAME:
        if (value == null) {
          unsetComponentName();
        } else {
          setComponentName((String)value);
        }
        break;

      case MAINCLASS:
        if (value == null) {
          unsetMainclass();
        } else {
          setMainclass((String)value);
        }
        break;

      case COMPONENT_INFO:
        if (value == null) {
          unsetComponentInfo();
        } else {
          setComponentInfo((ByteBuffer)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case COMPONENT_NAME:
        return getComponentName();

      case MAINCLASS:
        return getMainclass();

      case COMPONENT_INFO:
        return getComponentInfo();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case COMPONENT_NAME:
        return isSetComponentName();
      case MAINCLASS:
        return isSetMainclass();
      case COMPONENT_INFO:
        return isSetComponentInfo();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerComponent_args)
        return this.equals((registerComponent_args)that);
      return false;
    }

    public boolean equals(registerComponent_args that) {
      if (that == null)
        return false;

      boolean this_present_componentName = true && this.isSetComponentName();
      boolean that_present_componentName = true && that.isSetComponentName();
      if (this_present_componentName || that_present_componentName) {
        if (!(this_present_componentName && that_present_componentName))
          return false;
        if (!this.componentName.equals(that.componentName))
          return false;
      }

      boolean this_present_mainclass = true && this.isSetMainclass();
      boolean that_present_mainclass = true && that.isSetMainclass();
      if (this_present_mainclass || that_present_mainclass) {
        if (!(this_present_mainclass && that_present_mainclass))
          return false;
        if (!this.mainclass.equals(that.mainclass))
          return false;
      }

      boolean this_present_componentInfo = true && this.isSetComponentInfo();
      boolean that_present_componentInfo = true && that.isSetComponentInfo();
      if (this_present_componentInfo || that_present_componentInfo) {
        if (!(this_present_componentInfo && that_present_componentInfo))
          return false;
        if (!this.componentInfo.equals(that.componentInfo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_componentName = true && (isSetComponentName());
      list.add(present_componentName);
      if (present_componentName)
        list.add(componentName);

      boolean present_mainclass = true && (isSetMainclass());
      list.add(present_mainclass);
      if (present_mainclass)
        list.add(mainclass);

      boolean present_componentInfo = true && (isSetComponentInfo());
      list.add(present_componentInfo);
      if (present_componentInfo)
        list.add(componentInfo);

      return list.hashCode();
    }

    @Override
    public int compareTo(registerComponent_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetComponentName()).compareTo(other.isSetComponentName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetComponentName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.componentName, other.componentName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetMainclass()).compareTo(other.isSetMainclass());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetMainclass()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mainclass, other.mainclass);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetComponentInfo()).compareTo(other.isSetComponentInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetComponentInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.componentInfo, other.componentInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerComponent_args(");
      boolean first = true;

      sb.append("componentName:");
      if (this.componentName == null) {
        sb.append("null");
      } else {
        sb.append(this.componentName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("mainclass:");
      if (this.mainclass == null) {
        sb.append("null");
      } else {
        sb.append(this.mainclass);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("componentInfo:");
      if (this.componentInfo == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.componentInfo, sb);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class registerComponent_argsStandardSchemeFactory implements SchemeFactory {
      public registerComponent_argsStandardScheme getScheme() {
        return new registerComponent_argsStandardScheme();
      }
    }

    private static class registerComponent_argsStandardScheme extends StandardScheme<registerComponent_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerComponent_args struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // COMPONENT_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.componentName = iprot.readString();
                struct.setComponentNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // MAINCLASS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.mainclass = iprot.readString();
                struct.setMainclassIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 3: // COMPONENT_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.componentInfo = iprot.readBinary();
                struct.setComponentInfoIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerComponent_args struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.componentName != null) {
          oprot.writeFieldBegin(COMPONENT_NAME_FIELD_DESC);
          oprot.writeString(struct.componentName);
          oprot.writeFieldEnd();
        }
        if (struct.mainclass != null) {
          oprot.writeFieldBegin(MAINCLASS_FIELD_DESC);
          oprot.writeString(struct.mainclass);
          oprot.writeFieldEnd();
        }
        if (struct.componentInfo != null) {
          oprot.writeFieldBegin(COMPONENT_INFO_FIELD_DESC);
          oprot.writeBinary(struct.componentInfo);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerComponent_argsTupleSchemeFactory implements SchemeFactory {
      public registerComponent_argsTupleScheme getScheme() {
        return new registerComponent_argsTupleScheme();
      }
    }

    private static class registerComponent_argsTupleScheme extends TupleScheme<registerComponent_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerComponent_args struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetComponentName()) {
          optionals.set(0);
        }
        if (struct.isSetMainclass()) {
          optionals.set(1);
        }
        if (struct.isSetComponentInfo()) {
          optionals.set(2);
        }
        oprot.writeBitSet(optionals, 3);
        if (struct.isSetComponentName()) {
          oprot.writeString(struct.componentName);
        }
        if (struct.isSetMainclass()) {
          oprot.writeString(struct.mainclass);
        }
        if (struct.isSetComponentInfo()) {
          oprot.writeBinary(struct.componentInfo);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerComponent_args struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(3);
        if (incoming.get(0)) {
          struct.componentName = iprot.readString();
          struct.setComponentNameIsSet(true);
        }
        if (incoming.get(1)) {
          struct.mainclass = iprot.readString();
          struct.setMainclassIsSet(true);
        }
        if (incoming.get(2)) {
          struct.componentInfo = iprot.readBinary();
          struct.setComponentInfoIsSet(true);
        }
      }
    }

  }

  public static class registerComponent_result implements org.apache.thrift.TBase<registerComponent_result, registerComponent_result._Fields>, java.io.Serializable, Cloneable, Comparable<registerComponent_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerComponent_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new registerComponent_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new registerComponent_resultTupleSchemeFactory());
    }

    public String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerComponent_result.class, metaDataMap);
    }

    public registerComponent_result() {
    }

    public registerComponent_result(
      String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public registerComponent_result(registerComponent_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public registerComponent_result deepCopy() {
      return new registerComponent_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public String getSuccess() {
      return this.success;
    }

    public registerComponent_result setSuccess(String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof registerComponent_result)
        return this.equals((registerComponent_result)that);
      return false;
    }

    public boolean equals(registerComponent_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true && (isSetSuccess());
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(registerComponent_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("registerComponent_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class registerComponent_resultStandardSchemeFactory implements SchemeFactory {
      public registerComponent_resultStandardScheme getScheme() {
        return new registerComponent_resultStandardScheme();
      }
    }

    private static class registerComponent_resultStandardScheme extends StandardScheme<registerComponent_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, registerComponent_result struct) throws TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, registerComponent_result struct) throws TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class registerComponent_resultTupleSchemeFactory implements SchemeFactory {
      public registerComponent_resultTupleScheme getScheme() {
        return new registerComponent_resultTupleScheme();
      }
    }

    private static class registerComponent_resultTupleScheme extends TupleScheme<registerComponent_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, registerComponent_result struct) throws TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, registerComponent_result struct) throws TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
